config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
  get 'states/index'
  end

  namespace :admin do
  get 'states/new'
  end

  namespace :admin do
  get 'states/create'
  end

  get 'comments/create'

  namespace :admin do
    get 'permissions/index'
  end

  namespace :admin do
    root to: 'base#index'
    resources :users do
      resources :permissions

      put 'permissions', to: 'permissions#set', as: 'set_permissions'
    end

    resources :states do
      member do
        get :make_default
      end
    end
  end

  get 'sessions/new'

  get 'users/new'

  get 'users/create'

  get 'users/show'

  get 'signin', to: 'sessions#new'

  post 'signin', to: 'sessions#create'

  delete 'signout', to: 'sessions#destroy', as: 'signout'
  root 'projects#index' 

  resources :projects do
    resources :tickets
  end

  resources :tickets do
    resources :comments
  end

  resources :files

  resources :users
end

app/models/state.rb
class State < ActiveRecord::Base
  def to_s
    name
  end

  def default!
    current_default_state = State.find_by_default(true)

    self.default = true
    self.save!

    if current_default_state
      current_default_state.default = false
      current_default_state.save!
    end
  end
end

app/controllers/admin/states_controller.rb
class Admin::StatesController < ApplicationController
  def index
    @states = State.all
  end

  def new
    @state = State.new
  end

  def create
    @state = State.new(state_params)
    if @state.save
      flash[:notice] = 'State has been created.'
      redirect_to admin_states_path
    else
      flash[:alert] = 'State has not been created.'
      render action: 'new'
    end
  end

  def make_default
    state = State.find(params[:id])
    state.default!

    flash[:notice] = "#{state.name} is now the default state."
    redirect_to admin_states_path
  end

  private
  def state_params
    params.require(:state).permit(:name)
  end

end

app/helpers/admin/states_helper.rb
module Admin::StatesHelper
end

app/views/admin/states/_form.html.erb
<%= form_for [:admin, @state] do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <%= f.submit %>
<% end %>

app/views/admin/states/create.html.erb
<h1>Admin::States#create</h1>
<p>Find me in app/views/admin/states/create.html.erb</p>

app/views/admin/states/index.html.erb
<h1>States</h1>
<ul id="states">
  <% @states.each do |state| %>
    <li id="state_<%= state.id %>">
      <%= state.name %>
      <%= link_to 'Make Default', make_default_admin_state_path(state) %>
    </li>
  <% end %>
</ul>

<%= link_to 'New State', new_admin_state_path %>

app/views/admin/states/new.html.erb
<h1>Add new state</h1>
<%= render 'form' %>