config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
  get 'states/index'
  end

  namespace :admin do
  get 'states/new'
  end

  namespace :admin do
  get 'states/create'
  end

  get 'comments/create'

  namespace :admin do
    get 'permissions/index'
  end

  namespace :admin do
    root to: 'base#index'
    resources :users do
      resources :permissions

      put 'permissions', to: 'permissions#set', as: 'set_permissions'
    end

    resources :states do
      member do
        get :make_default
      end
    end
  end

  get 'sessions/new'

  get 'users/new'

  get 'users/create'

  get 'users/show'

  get 'signin', to: 'sessions#new'

  post 'signin', to: 'sessions#create'

  delete 'signout', to: 'sessions#destroy', as: 'signout'
  root 'projects#index' 

  resources :projects do
    resources :tickets
  end

  resources :tickets do
    resources :comments
  end

  resources :files

  resources :users
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
  <%if content_for?(:title) %>
    <%= yield :title %>
  <% else %>
    Ticketee
  <% end %>>
  </title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <style>
    <% for state in @states %>
      .state_<%= state.name.parameterize %> {
          background: <%= state.background %>;
          color: <%= state.color %>;
      }
    <% end %>
  </style>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
  <% if current_user %>
    Signed in as <%= current_user.email %>
    <%= link_to 'Sign out', signout_path, method: :delete %>
    <% admins_only do %>
      <%= link_to 'Admin', admin_root_path %>
    <% end %>
  <% else %>
    <ul>
      <li>
        <%= link_to "Sign up", new_user_path %>
      </li>
      <li>
        <%= link_to "Sign in", signin_path %>
      </li>
    </ul>
  <% end %>
</nav>
  <% flash.each do |key, value| %>
    <div class='flash' id='<%= key %>' >
      <%= value %>
    </div>
  <% end %>
<%= yield %>

</body>
</html>